alertmanager:
  ## Alertmanager configuration directives
  ## Ref: https://prometheus.io/docs/alerting/configuration/
  ##
  config:
    global:
      resolve_timeout: 5m

    receivers:
      - name: default-receiver
        slack_configs:
          - channel: '#sys-k8s-cs-alarm'
            send_resolved: true
            api_url: "https://hooks.slack.com/services/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"

    route:
      group_by: ['job']
      group_interval: 5m
      group_wait: 30s
      receiver: default-receiver
      repeat_interval: 3h

  ingress:
    ## If true, Alertmanager Ingress will be created
    enabled: true

    ## ingress host
    fqdn: "alertmanager.ke-cs.dev.qiniu.io"

  ## Resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # requests:
    #   memory: 400Mi

  service:
    ## Service type
    type: ClusterIP

  ## Alertmanager StorageSpec for persistent data
  ## Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/prometheus.md#storagespec
  ##
  storageSpec:
    class: ceph-rbd
    resources:
      requests:
        storage: 2Gi

prometheus:
  ingress:
    enabled: true

    ## ingress host
    fqdn: "prometheus.ke-cs.dev.qiniu.io"

  ## Number of Prometheus replicas desired
  ##
  replicaCount: 1

  ## Resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources: {}
    # requests:
    #   memory: 400Mi

  ## How long to retain metrics
  ##
  retention: 24h

  service:
    type: ClusterIP

  ## Prometheus StorageSpec for persistent data
  ## Ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/prometheus.md#storagespec
  ##
  storageSpec:
    class: ceph-rbd
    resources:
      requests:
        storage: 100Gi

  rules:
    specifiedInValues: true
    value: {}

grafana:
  adminUser: "admin"
  adminPassword: "admin"

  service:
    type: ClusterIP

  storageSpec:
    class: ceph-rbd
    accessMode: ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

  resources: {}
    # requests:
    #   memory: 400Mi

  ingress:
    enabled: true

    fqdn: "grafana.ke-cs.dev.qiniu.io"
